Repository UwUClub/R-Type, pull requests merged in 2023-10, with the labels that each got.

#19 RT-27 Update RFC (again)
  doc/RFC.md
Labels: documentation

#16 Rt 26 move player system
  .gitignore
  CMakeLists.txt
  Dependencies.cmake
  assets/sprites/r-typesheet42.png
  cmake/FindSDL2.cmake
  src/client/CMakeLists.txt
  src/client/SDLDisplayClass.cpp
  src/client/SDLDisplayClass.hpp
  src/client/System+DisplayEntities.cpp
  src/client/System+GetInput.cpp
  src/client/System+LoadTextures.cpp
  src/client/System+MovePlayer.cpp
  src/client/System.hpp
  src/client/main.cpp
  src/ecs/CMakeLists.txt
  src/ecs/Event/CMakeLists.txt
  src/ecs/Event/KeyboardEvent.hpp
  src/ecs/Utils.hpp
  src/ecs/World.hpp
Labels: enhancement

#21 Fixed the compilation
  Dependencies.cmake
  src/client/CMakeLists.txt
  src/client/System+DisplayEntities.cpp
  src/client/main.cpp
  src/client/systems/CMakeLists.txt
  src/client/systems/System+DisplayEntities.cpp
  src/client/systems/System+GetInput.cpp
  src/client/systems/System+LoadTextures.cpp
  src/client/systems/System+MovePlayer.cpp
  src/client/systems/System+Parallax.cpp
  src/client/systems/System+SDLQuit.cpp
  src/client/systems/System.hpp
  src/ecs/World.hpp
Labels: bug, Fix

#20 RT-45 -> dev
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  Dependencies.cmake
  Dockerfile
  DockerfileWindows
  Jenkinsfile
  src/client/systems/System+DisplayEntities.cpp
  src/client/systems/System+LoadTextures.cpp
  src/client/systems/System+MovePlayer.cpp
Labels: enhancement, cicd

#23 Rt 45 new cicd
  .github/workflows/ci.yml
Labels: enhancement, cicd

#25 Fix tags
  .github/workflows/ci.yml
Labels: enhancement, cicd

#26 Fix tags
  .github/workflows/ci.yml
Labels: enhancement, cicd

#24 Refactor lot of parts
  Dependencies.cmake
  assets/sprites/background.png
  src/client/CMakeLists.txt
  src/client/SDLDisplayClass.cpp
  src/client/SDLDisplayClass.hpp
  src/client/components/CMakeLists.txt
  src/client/components/Components.hpp
  src/client/components/LoadedSprite.hpp
  src/client/components/Speed.hpp
  src/client/components/TypeEntity.hpp
  src/client/main.cpp
  src/client/systems/System+DisplayEntities.cpp
  src/client/systems/System+GetInput.cpp
  src/client/systems/System+LoadTextures.cpp
  src/client/systems/System+MovePlayer.cpp
  src/client/systems/System+Parallax.cpp
  src/client/systems/System+SDLQuit.cpp
  src/client/systems/System.hpp
  src/ecs/Utils.hpp
  src/ecs/World.hpp
Labels: refactor, Fix

#22 Refactor ClientEvent and ServerToClientPacket format
  src/client/main.cpp
  src/ecs/World.hpp
  src/rtype_protocol/ClientGameEvent.cpp
  src/rtype_protocol/ClientGameEvent.hpp
  src/rtype_protocol/Packets.hpp
Labels: enhancement

#27 Rt 36 paralax system
  .github/actions/setup_cache/action.yml
  .github/workflows/ci.yml
  ProjectOptions.cmake
  src/client/SDLDisplayClass.cpp
  src/client/components/LoadedSprite.hpp
  src/client/components/Speed.hpp
  src/client/components/TypeEntity.hpp
  src/client/main.cpp
  src/client/systems/CMakeLists.txt
  src/client/systems/System+DisplayEntities.cpp
  src/client/systems/System+GetInput.cpp
  src/client/systems/System+MoveBackground.cpp
  src/client/systems/System+SDLQuit.cpp
  src/client/systems/System.hpp
  src/ecs/World.hpp
Labels: documentation, enhancement

#29 Added some UT for World
  src/client/components/Speed.hpp
  src/client/main.cpp
  src/ecs/World.hpp
  test/CMakeLists.txt
  test/tests+World.cpp
Labels: tests

#30 RT-48 -> DEV
  .github/actions/setup_cache/action.yml
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
Labels: enhancement, cicd

#31 Add moveEnemies system
  src/client/SDLDisplayClass.cpp
  src/client/SDLDisplayClass.hpp
  src/client/Values.hpp
  src/client/main.cpp
  src/client/network/ClientNetworkHandler.hpp
  src/client/systems/CMakeLists.txt
  src/client/systems/System+GetInput.cpp
  src/client/systems/System+LoadTextures.cpp
  src/client/systems/System+MoveBackground.cpp
  src/client/systems/System+MoveEnemies.cpp
  src/client/systems/System+MovePlayer.cpp
  src/client/systems/System+SDLQuit.cpp
  src/client/systems/System+SpawnEnemies.cpp
  src/client/systems/System.hpp
Labels: enhancement

#33 Add Shoot and move system for player bullets
  assets/sprites/r-typesheet2.png
  src/client/Values.hpp
  src/client/main.cpp
  src/client/systems/CMakeLists.txt
  src/client/systems/System+MoveMissiles.cpp
  src/client/systems/System+ShootMissiles.cpp
  src/client/systems/System.hpp
Labels: enhancement

#35 Rt 43 destroy enemy system
  src/client/SDLDisplayClass.cpp
  src/client/SDLDisplayClass.hpp
  src/client/Values.hpp
  src/client/components/Components.hpp
  src/client/components/HitBox.hpp
  src/client/components/IsAlive.hpp
  src/client/components/LoadedSprite.hpp
  src/client/main.cpp
  src/client/systems/CMakeLists.txt
  src/client/systems/System+DestroyEnemy.cpp
  src/client/systems/System+HandleEnemyDeath.cpp
  src/client/systems/System+LoadTextures.cpp
  src/client/systems/System+MoveEnemies.cpp
  src/client/systems/System+MoveMissiles.cpp
  src/client/systems/System+ShootMissiles.cpp
  src/client/systems/System+SpawnEnemies.cpp
  src/client/systems/System.hpp
  src/ecs/SparseArray.hpp
Labels: enhancement

#34 RT-42 server game logic
  src/CMakeLists.txt
  src/client/CMakeLists.txt
  src/client/SDLDisplayClass.cpp
  src/client/SDLDisplayClass.hpp
  src/client/components/TypeEntity.hpp
  src/client/main.cpp
  src/client/network/ClientNetworkHandler.cpp
  src/client/network/ClientNetworkHandler.hpp
  src/client/systems/CMakeLists.txt
  src/client/systems/System+CreatePlayer.cpp
  src/client/systems/System+MovePlayer.cpp
  src/client/systems/System+ShootMissiles.cpp
  src/client/systems/System+SpawnEnemies.cpp
  src/client/systems/System+UpdatePlayerPos.cpp
  src/client/systems/System.hpp
  src/ecs/CMakeLists.txt
  src/ecs/Event/CMakeLists.txt
  src/ecs/Event/EventManager.cpp
  src/ecs/Event/EventManager.hpp
  src/rtype/CMakeLists.txt
  src/rtype/ClientGameEvent.cpp
  src/rtype/ClientGameEvent.hpp
  src/rtype/Packets.hpp
  src/rtype/ServerGameEvent.cpp
  src/rtype/ServerGameEvent.hpp
  src/rtype/components/CMakeLists.txt
  src/rtype/components/Components.hpp
  src/rtype/components/HitBox.hpp
  src/rtype/components/IsAlive.hpp
  src/rtype/components/LoadedSprite.hpp
  src/rtype/components/Speed.hpp
  src/rtype/components/TypeEntity.hpp
  src/rtype_protocol/ClientGameEvent.cpp
  src/rtype_protocol/ServerGameEvent.cpp
  src/rtype_protocol/ServerGameEvent.hpp
  src/server/main.cpp
  src/server/network/CMakeLists.txt
  src/server/network/ServerNetworkHandler.cpp
  src/server/network/ServerNetworkHandler.hpp
  src/server/systems/CMakeLists.txt
  src/server/systems/System+MovePlayer.cpp
  src/server/systems/System+WelcomePlayers.cpp
  src/server/systems/System.hpp
  test/tests+World.cpp
Labels: enhancement

#36 Rt 51 enemies missiles system
  assets/sprites/r-typesheet16.png
  src/client/Values.hpp
  src/client/main.cpp
  src/client/systems/CMakeLists.txt
  src/client/systems/System+CreatePlayer.cpp
  src/client/systems/System+EnemyMissiles.cpp
  src/client/systems/System+HandleEnemyDeath.cpp
  src/client/systems/System+MoveMissiles.cpp
  src/client/systems/System+PlayerDeath.cpp
  src/client/systems/System+UpdatePlayerPos.cpp
  src/client/systems/System.hpp
  src/ecs/Event/EventManager.cpp
  src/ecs/Event/EventManager.hpp
  src/rtype/components/TypeEntity.hpp
  src/server/systems/System+MovePlayer.cpp
  src/server/systems/System+WelcomePlayers.cpp
Labels: enhancement

#38 Rt 52 player death system
  README.md
  src/client/main.cpp
  src/client/systems/CMakeLists.txt
  src/client/systems/System+CreatePlayer.cpp
  src/client/systems/System+HandlePlayerDeath.cpp
  src/client/systems/System+LoadTextures.cpp
  src/client/systems/System+MovePlayer.cpp
  src/client/systems/System+PlayerDeath.cpp
  src/client/systems/System+ShootMissiles.cpp
  src/client/systems/System.hpp
Labels: enhancement

#39 RT-49 check packet received (+network refacto)
  Dependencies.cmake
  doc/RFC.md
  src/client/CMakeLists.txt
  src/client/main.cpp
  src/client/network/CMakeLists.txt
  src/client/network/ClientHandler.cpp
  src/client/network/ClientHandler.hpp
  src/client/network/ClientNetworkHandler.cpp
  src/client/network/ClientNetworkHandler.hpp
  src/client/systems/System+CreatePlayer.cpp
  src/client/systems/System+MovePlayer.cpp
  src/client/systems/System+UpdatePlayerPos.cpp
  src/rtype/CMakeLists.txt
  src/rtype/ClientGameEvent.cpp
  src/rtype/ClientGameEvent.hpp
  src/rtype/NetworkHandler.cpp
  src/rtype/NetworkHandler.hpp
  src/rtype/Packets.hpp
  src/rtype/ServerGameEvent.cpp
  src/rtype/ServerGameEvent.hpp
  src/rtype/Values.hpp
  src/server/main.cpp
  src/server/network/CMakeLists.txt
  src/server/network/ServerHandler.cpp
  src/server/network/ServerHandler.hpp
  src/server/network/ServerNetworkHandler.cpp
  src/server/systems/System+MovePlayer.cpp
  src/server/systems/System+WelcomePlayers.cpp
Labels: enhancement, refactor

#40 RT-53 network: enemies (spawn and move)
  doc/RFC.md
  src/client/SDLDisplayClass.hpp
  src/client/main.cpp
  src/client/systems/CMakeLists.txt
  src/client/systems/System+CreateEnemy.cpp
  src/client/systems/System+CreatePlayer.cpp
  src/client/systems/System+SpawnEnemies.cpp
  src/client/systems/System.hpp
  src/rtype/ClientGameEvent.hpp
  src/server/CMakeLists.txt
  src/server/main.cpp
  src/server/network/ServerHandler.hpp
  src/server/systems/CMakeLists.txt
  src/server/systems/System+MoveEnemies.cpp
  src/server/systems/System+SpawnEnemies.cpp
  src/server/systems/System+WelcomePlayers.cpp
  src/server/systems/System.hpp
  src/server/timers/CMakeLists.txt
  src/server/timers/Timer+SpawnEnemies.hpp
  src/server/timers/Timer.cpp
  src/server/timers/Timer.hpp
Labels: enhancement

#42 RT-38 -> dev
  Dependencies.cmake
  src/client/CMakeLists.txt
  src/rtype/CMakeLists.txt
  src/server/network/CMakeLists.txt
Labels: Fix

#44 Added first iteration of the How To
  doc/HowTo.md
  src/ecs/World.hpp
Labels: documentation

#47 RT-63 disconnect packet
  src/client/main.cpp
  src/client/systems/System.hpp
  src/client/systems/bot/CMakeLists.txt
  src/client/systems/bot/System+TriggerBotDisconnect.cpp
  src/client/systems/enemy/System+MoveEnemy.cpp
  src/client/systems/missile/System+MoveMissiles.cpp
  src/rtype/events/ClientGameEvent.hpp
  src/rtype/events/ServerGameEvent.hpp
  src/server/main.cpp
  src/server/network/ServerHandler.cpp
  src/server/network/ServerHandler.hpp
  src/server/systems/System.hpp
  src/server/systems/player/CMakeLists.txt
  src/server/systems/player/System+DisconnectPlayer.cpp
Labels: enhancement

#45 RT-27 RFC v2
  doc/RFC.md
Labels: documentation

#46 Fix player hitbox
  src/client/systems/bot/System+BotHit.cpp
  src/server/main.cpp
  src/server/systems/System.hpp
  src/server/systems/player/System+PlayerHit.cpp
  src/server/systems/player/System+WelcomePlayer.cpp
Labels: Fix

#48 RT-57 player colors
  src/client/systems/bot/System+CreateBot.cpp
  src/rtype/CMakeLists.txt
  src/rtype/PlayerColor.hpp
  src/rtype/Values.hpp
  src/server/network/ServerHandler.cpp
  src/server/network/ServerHandler.hpp
  src/server/systems/player/System+WelcomePlayer.cpp
Labels: enhancement

#50 RT-64 wrong ip address crash
  src/client/main.cpp
  src/rtype/Values.hpp
  src/server/main.cpp
Labels: Fix

#51 RT-60 error message on room full
  assets/sprites/loading-message.png
  assets/sprites/server-full-message.png
  src/client/main.cpp
  src/client/systems/System.hpp
  src/client/systems/background/CMakeLists.txt
  src/client/systems/background/System+CreateBackground.cpp
  src/client/systems/graphic/CMakeLists.txt
  src/client/systems/graphic/System+CreateServerFullErrorMessage.cpp
  src/rtype/Values.hpp
  src/rtype/events/ClientGameEvent.hpp
  src/server/network/ServerHandler.cpp
  src/server/network/ServerHandler.hpp
  src/server/systems/player/System+WelcomePlayer.cpp
Labels: enhancement

#52 RT-65 handle wrong packet format
  src/client/systems/bot/System+CreateBot.cpp
  src/client/systems/bot/System+TriggerBotBonus.cpp
  src/client/systems/bot/System+TriggerBotDeath.cpp
  src/client/systems/bot/System+TriggerBotDisconnect.cpp
  src/client/systems/bot/System+TriggerBotShoot.cpp
  src/client/systems/bot/System+UpdateBotPosition.cpp
  src/client/systems/enemy/System+CreateEnemy.cpp
  src/client/systems/enemy/System+TriggerEnemyDeath.cpp
  src/client/systems/enemy/System+TriggerEnemyShoot.cpp
  src/client/systems/player/System+TriggerPlayerShoot.cpp
  src/server/systems/player/System+MovePlayer.cpp
  src/server/systems/player/System+PlayerShoot.cpp
Labels: enhancement, Fix

#53 Rt 58 create release
  .github/workflows/ci.yml
Labels: cicd, Fix

#57 Rt urgent mirror fix
  .github/workflows/mirroring.yml
  README.md
Labels: bug, Fix

#58 Rt urgent release
  .github/workflows/ci.yml
  .gitignore
  CMakeLists.txt
  Dependencies.cmake
  ProjectOptions.cmake
  README.md
  cmake/CompilerWarnings.cmake
  configured_files/CMakeLists.txt
  configured_files/config.hpp.in
  src/client/CMakeLists.txt
  src/client/SDLDisplayClass.cpp
  src/client/SDLDisplayClass.hpp
  src/client/main.cpp
  src/client/network/CMakeLists.txt
  src/client/systems/CMakeLists.txt
  src/client/systems/background/CMakeLists.txt
  src/client/systems/bonus/CMakeLists.txt
  src/client/systems/bot/CMakeLists.txt
  src/client/systems/enemy/CMakeLists.txt
  src/client/systems/graphic/CMakeLists.txt
  src/client/systems/missile/CMakeLists.txt
  src/client/systems/player/CMakeLists.txt
  src/ecs/CMakeLists.txt
  src/rtype/CMakeLists.txt
  src/rtype/components/CMakeLists.txt
  src/rtype/events/CMakeLists.txt
  src/server/CMakeLists.txt
  src/server/main.cpp
  src/server/network/CMakeLists.txt
  src/server/systems/CMakeLists.txt
  src/server/systems/bonus/CMakeLists.txt
  src/server/systems/enemy/CMakeLists.txt
  src/server/systems/missile/CMakeLists.txt
  src/server/systems/network/CMakeLists.txt
  src/server/systems/player/CMakeLists.txt
Labels: cicd

#63 RT-72 fix windows abort and wrong packet format crash
  src/rtype/NetworkHandler.cpp
  src/rtype/NetworkHandler.hpp
  src/rtype/Packets.hpp
  src/rtype/events/ClientGameEvent.cpp
  src/rtype/events/ClientGameEvent.hpp
  src/rtype/events/ServerGameEvent.cpp
  src/rtype/events/ServerGameEvent.hpp
  src/server/network/ServerHandler.cpp
  src/server/network/ServerHandler.hpp
  src/server/systems/bonus/System+MoveSpeed.cpp
  src/server/systems/enemy/System+EnemyShoot.cpp
  src/server/systems/enemy/System+KillEnemy.cpp
  src/server/systems/enemy/System+SpawnEnemy.cpp
  src/server/systems/network/System+ReceiveAknowledgment.cpp
  src/server/systems/player/System+DisconnectPlayer.cpp
  src/server/systems/player/System+KillPlayer.cpp
  src/server/systems/player/System+MovePlayer.cpp
  src/server/systems/player/System+PlayerShoot.cpp
  src/server/systems/player/System+WelcomePlayer.cpp
Labels: Fix

#65 RT-38 -> DEV
  .readthedocs.yaml
Labels: documentation, enhancement

#66 Fixed events deletion
  src/client/systems/bot/System+CreateBot.cpp
  src/client/systems/bot/System+TriggerBotBonus.cpp
  src/client/systems/bot/System+TriggerBotDeath.cpp
  src/client/systems/bot/System+TriggerBotDisconnect.cpp
  src/client/systems/bot/System+TriggerBotShoot.cpp
  src/client/systems/bot/System+UpdateBotPosition.cpp
  src/client/systems/enemy/System+CreateEnemy.cpp
  src/client/systems/enemy/System+TriggerEnemyDeath.cpp
  src/client/systems/enemy/System+TriggerEnemyShoot.cpp
  src/client/systems/graphic/System+CreateServerFullErrorMessage.cpp
  src/ecs/Event/EventManager.hpp
  src/ecs/Event/KeyboardEvent.hpp
  src/ecs/Event/MouseEvent.hpp
  src/ecs/Event/WindowEvent.hpp
  src/rtype/events/ClientGameEvent.hpp
  src/rtype/events/ServerGameEvent.hpp
  src/server/systems/bonus/System+MoveSpeed.cpp
  src/server/systems/network/System+ReceiveAknowledgment.cpp
  src/server/systems/player/System+DisconnectPlayer.cpp
  src/server/systems/player/System+MovePlayer.cpp
  src/server/systems/player/System+PlayerShoot.cpp
  src/server/systems/player/System+WelcomePlayer.cpp
Labels: bug, Fix

#67 Fixed events deletion
  src/server/systems/bonus/System+MoveSpeed.cpp
  src/server/systems/network/System+ReceiveAknowledgment.cpp
  src/server/systems/player/System+DisconnectPlayer.cpp
  src/server/systems/player/System+MovePlayer.cpp
  src/server/systems/player/System+PlayerShoot.cpp
  src/server/systems/player/System+WelcomePlayer.cpp
Labels: Fix

#68 RT-71 Network fixes and improvements
  src/client/CMakeLists.txt
  src/client/network/ClientHandler.cpp
  src/client/systems/player/System+MovePlayer.cpp
  src/rtype/CMakeLists.txt
  src/rtype/NetworkHandler.cpp
  src/rtype/NetworkHandler.hpp
  src/rtype/Packets.hpp
  src/rtype/Serialization.hpp
  src/rtype/Values.hpp
  src/rtype/events/ClientGameEvent.hpp
  src/rtype/events/ServerGameEvent.hpp
  src/server/CMakeLists.txt
  src/server/network/ServerHandler.cpp
  src/server/network/ServerHandler.hpp
  src/server/systems/bonus/System+MoveSpeed.cpp
  src/server/systems/network/System+HandleClientCrash.cpp
  src/server/systems/player/System+MovePlayer.cpp
  src/server/systems/player/System+PlayerShoot.cpp
  src/server/systems/player/System+WelcomePlayer.cpp
Labels: enhancement, Fix

#71 Fixed crash
  src/server/network/ServerHandler.cpp
  src/server/systems/bonus/System+MoveSpeed.cpp
  src/server/systems/player/System+DisconnectPlayer.cpp
Labels: Fix

#75 Added a font
  assets/font.ttf
  config/r-type.json
  src/client/systems/background/System+CreateBackground.cpp
  src/client/systems/player/System+TriggerPlayerShoot.cpp
  src/server/systems/enemy/System+KillEnemy.cpp
  src/server/systems/player/System+KillPlayer.cpp
  src/server/systems/player/System+PlayerHit.cpp
Labels: enhancement

#73 RT-85 refacto network
  config/player_1.json
  config/player_2.json
  config/player_3.json
  config/player_4.json
  src/client/main.cpp
  src/client/network/ClientHandler.cpp
  src/client/network/ClientHandler.hpp
  src/client/network/PacketFactory.hpp
  src/client/systems/System.hpp
  src/client/systems/background/System+CreateBackground.cpp
  src/client/systems/background/System+MoveBackground.cpp
  src/client/systems/bonus/CMakeLists.txt
  src/client/systems/bonus/System+TriggerBonus.cpp
  src/client/systems/bot/CMakeLists.txt
  src/client/systems/bot/System+CreateBot.cpp
  src/client/systems/bot/System+TriggerBotBonus.cpp
  src/client/systems/bot/System+TriggerBotDeath.cpp
  src/client/systems/bot/System+TriggerBotDisconnect.cpp
  src/client/systems/bot/System+TriggerBotShoot.cpp
  src/client/systems/bot/System+UpdateBotPosition.cpp
  src/client/systems/enemy/System+CreateEnemy.cpp
  src/client/systems/enemy/System+TriggerEnemyDeath.cpp
  src/client/systems/enemy/System+TriggerEnemyShoot.cpp
  src/client/systems/graphic/System+CreateServerFullErrorMessage.cpp
  src/client/systems/player/System+MovePlayer.cpp
  src/client/systems/player/System+TriggerPlayerShoot.cpp
  src/rtype/CMakeLists.txt
  src/rtype/ClientPackets.hpp
  src/rtype/NetworkHandler.cpp
  src/rtype/NetworkHandler.hpp
  src/rtype/Packet.hpp
  src/rtype/Packets.hpp
  src/rtype/Serialization.hpp
  src/rtype/ServerPackets.hpp
  src/rtype/Values.hpp
  src/rtype/events/ClientGameEvent.cpp
  src/rtype/events/ClientGameEvent.hpp
  src/rtype/events/ServerGameEvent.cpp
  src/rtype/events/ServerGameEvent.hpp
  src/server/main.cpp
  src/server/network/PacketFactory.hpp
  src/server/network/ServerHandler.cpp
  src/server/network/ServerHandler.hpp
  src/server/systems/System.hpp
  src/server/systems/bonus/CMakeLists.txt
  src/server/systems/bonus/System+MoveBonus.cpp
  src/server/systems/bonus/System+MoveSpeed.cpp
  src/server/systems/bonus/System+TriggerBonus.cpp
  src/server/systems/enemy/System+EnemyShoot.cpp
  src/server/systems/enemy/System+KillEnemy.cpp
  src/server/systems/enemy/System+SpawnEnemy.cpp
  src/server/systems/network/System+HandleClientCrash.cpp
  src/server/systems/network/System+ReceiveAknowledgment.cpp
  src/server/systems/player/System+DisconnectPlayer.cpp
  src/server/systems/player/System+KillPlayer.cpp
  src/server/systems/player/System+MovePlayer.cpp
  src/server/systems/player/System+PlayerShoot.cpp
  src/server/systems/player/System+WelcomePlayer.cpp
Labels: enhancement

#78 RT-68 RFC updates
  doc/RFC.md
Labels: documentation
