Repository UwUClub/R-Type, pull requests merged in 2023-09, with the labels that each got.

#1 RT-11-doxygen -> dev
  .github/workflows/auto-clang-format.yml
  .github/workflows/ci.yml
  .github/workflows/deploy_github_pages.yml
  doxyfile
  src/client/main.cpp
  src/server/main.cpp
  test/tests.cpp
Labels: documentation, enhancement, cicd

#2 Rt 8 ecs refacto
  .clang-format
  .gitignore
  cmake/_FORTIFY_SOURCE.hpp
  src/CMakeLists.txt
  src/client/main.cpp
  src/ecs/CMakeLists.txt
  src/ecs/Event/CMakeLists.txt
  src/ecs/Event/Event.cpp
  src/ecs/Event/Event.hpp
  src/ecs/Event/EventManager.cpp
  src/ecs/Event/EventManager.hpp
  src/ecs/Event/KeyboardEvent.cpp
  src/ecs/Event/KeyboardEvent.hpp
  src/ecs/Event/MouseEvent.cpp
  src/ecs/Event/MouseEvent.hpp
  src/ecs/Event/WindowEvent.cpp
  src/ecs/Event/WindowEvent.hpp
  src/ecs/SparseArray.hpp
  src/ecs/Utils.hpp
  src/ecs/World.hpp
  src/server/main.cpp
  test/tests.cpp
Labels: documentation, enhancement, refactor

#3 Rt 10 read me - First PR
  README.md
Labels: documentation

#5 Rt 25 ressource manager
  src/CMakeLists.txt
  src/client/CMakeLists.txt
  src/client/main.cpp
  src/ecs/CMakeLists.txt
  src/ecs/Event/EventManager.cpp
  src/ecs/Resources/CMakeLists.txt
  src/ecs/Resources/ResourcesManager.hpp
  src/ecs/Utils.hpp
  src/ecs/World.hpp
  src/server/CMakeLists.txt
Labels: documentation, enhancement

#6 Upload template for isse and pr
  .github/issue_template.md
  .github/pull_request_template.md
  README_docker.md
Labels: documentation, enhancement, cicd

#7 RT-20 -> dev
  .github/workflows/codeql-analysis.yml
  .github/workflows/mirroring.yml
  ProjectOptions.cmake
Labels: enhancement, cicd

#9 RT-20 -> dev
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  LICENSE
  SECURITY.md
Labels: documentation, enhancement

#10 RT-20 -> dev
  .github/workflows/codeql-analysis.yml
Labels: bug

#11 Updated Event Manager to use pointers
  src/ecs/Event/EventManager.cpp
  src/ecs/Event/EventManager.hpp
Labels: bug

#12 Rt 39 refarctor resources manager
  src/ecs/Resources/ResourcesManager.hpp
Labels: documentation, enhancement, refactor

#13 Rt 31 get user input system
  .github/workflows/codeql-analysis.yml
  .github/workflows/mirroring.yml
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  ECS_archi.mdj
  LICENSE
  ProjectOptions.cmake
  SECURITY.md
  src/client/CMakeLists.txt
  src/client/SDLDisplayClass.cpp
  src/client/SDLDisplayClass.hpp
  src/client/System.cpp
  src/client/System.hpp
  src/client/main.cpp
  src/ecs/Event/EventManager.cpp
  src/ecs/Event/EventManager.hpp
  src/ecs/Event/KeyboardEvent.hpp
  src/ecs/Resources/ResourcesManager.hpp
  src/ecs/World.hpp
Labels: enhancement

#14 Rt 32 display of entities system
  Dependencies.cmake
  assets/sprites/r-typesheet42.png
  src/client/CMakeLists.txt
  src/client/SDLDisplayClass.cpp
  src/client/System.cpp
  src/client/System.hpp
  src/client/main.cpp
  src/ecs/Utils.hpp
Labels: enhancement

#15 Removed Resources
  src/ecs/CMakeLists.txt
  src/ecs/Resources/CMakeLists.txt
  src/ecs/Resources/ResourcesManager.hpp
Labels: refactor

#17 RT-27 RFC
  doc/RFC.md
Labels: documentation

#18 RT-27 Update RFC.md
  doc/RFC.md
Labels: documentation
